### ISSUE TITLE
Example of color styling

### ISSUE THREAD

**Issue by dicksonca** [mopcweb/angular-breadcrumbs-light#6]
Hello,

In your demo, could you please provide some examples of the intended usage of custom classes for styling?

Thank you

**Comment by mopcweb** [comment]
Hello, @dicksonca 
Example of calling component in your app:

`<angular-breadcrumbs-light 
  [routes]="routes"
  notFoundIcon='❗'
  noTitlesOnMobile="true"
  [customClasses]="{
    root: 'customRootClass',
    currentLink: 'customCurrentLinkClass',
    separator: 'customSeparatorClass'
  }"
>
</angular-breadcrumbs-light>`

And add this classes in your global stylesheet (by default: src/styles.css):

`.customRootClass {
  margin: 40px;
}

.customCurrentLinkClass {
  color: green !important;
}

.customSeparatorClass {
  color: red;
  position: relative;
}

.customSeparatorClass::after {
  color: yellow;
  display: block;
  content: 'sep text from css'
}`

I've implemented this demo [here](https://stackblitz.com/edit/angular-breadcrumbs-light-custom-classes?embed=1&file=src/app/pages/dashboard/dashboard.component.html)
